/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait ArtistsApi: Send + Sync {
    /// POST /artists/{id}/relationships/following
    ///
    /// Adds item(s) to following relationship.
    async fn add_artist_followers<
        'id,
        'country_code,
        'artist_following_relationship_add_operation_payload,
    >(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        artist_following_relationship_add_operation_payload: Option<
            models::ArtistFollowingRelationshipAddOperationPayload,
        >,
    ) -> Result<(), Error<AddArtistFollowersError>>;

    /// POST /artists
    ///
    /// Creates a new artist.
    async fn create_artist<'artist_create_operation_payload>(
        &self,
        artist_create_operation_payload: Option<models::ArtistCreateOperationPayload>,
    ) -> Result<models::ArtistsSingleResourceDataDocument, Error<CreateArtistError>>;

    /// DELETE /artists/{id}/relationships/following
    ///
    /// Deletes item(s) from following relationship.
    async fn delete_artist_followers<'id, 'artist_following_relationship_remove_operation_payload>(
        &self,
        id: &'id str,
        artist_following_relationship_remove_operation_payload: Option<
            models::ArtistFollowingRelationshipRemoveOperationPayload,
        >,
    ) -> Result<(), Error<DeleteArtistFollowersError>>;

    /// GET /artists/{id}
    ///
    /// Retrieves single artist by id.
    async fn get_artist<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsSingleResourceDataDocument, Error<GetArtistError>>;

    /// GET /artists/{id}/relationships/albums
    ///
    /// Retrieves albums relationship.
    async fn get_artist_albums<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistAlbumsError>>;

    /// GET /artists/{id}/relationships/biography
    ///
    /// Retrieves biography relationship.
    async fn get_artist_artist_biography<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsSingleRelationshipDataDocument, Error<GetArtistArtistBiographyError>>;

    /// GET /artists/{id}/relationships/roles
    ///
    /// Retrieves roles relationship.
    async fn get_artist_artist_roles<'id, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistArtistRolesError>>;

    /// GET /artists/{id}/relationships/following
    ///
    /// Retrieves following relationship.
    async fn get_artist_follower<'id, 'viewer_context, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        viewer_context: Option<&'viewer_context str>,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsFollowingMultiRelationshipDataDocument, Error<GetArtistFollowerError>>;

    /// GET /artists/{id}/relationships/followers
    ///
    /// Retrieves followers relationship.
    async fn get_artist_followers<'id, 'viewer_context, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        viewer_context: Option<&'viewer_context str>,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsFollowersMultiRelationshipDataDocument, Error<GetArtistFollowersError>>;

    /// GET /artists/{id}/relationships/owners
    ///
    /// Retrieves owners relationship.
    async fn get_artist_owners<'id, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistOwnersError>>;

    /// GET /artists/{id}/relationships/profileArt
    ///
    /// Retrieves profileArt relationship.
    async fn get_artist_profile_art<'id, 'country_code, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistProfileArtError>>;

    /// GET /artists/{id}/relationships/radio
    ///
    /// Retrieves radio relationship.
    async fn get_artist_radio<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistRadioError>>;

    /// GET /artists/{id}/relationships/similarArtists
    ///
    /// Retrieves similarArtists relationship.
    async fn get_artist_similar_artists<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistSimilarArtistsError>>;

    /// GET /artists/{id}/relationships/trackProviders
    ///
    /// Retrieves trackProviders relationship.
    async fn get_artist_track_providers<'id, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<
        models::ArtistsTrackProvidersMultiRelationshipDataDocument,
        Error<GetArtistTrackProvidersError>,
    >;

    /// GET /artists/{id}/relationships/tracks
    ///
    /// Retrieves tracks relationship.
    async fn get_artist_tracks<'id, 'collapse_by, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        collapse_by: &'collapse_by str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistTracksError>>;

    /// GET /artists/{id}/relationships/videos
    ///
    /// Retrieves videos relationship.
    async fn get_artist_videos<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistVideosError>>;

    /// GET /artists
    ///
    /// Retrieves multiple artists by available filters, or without if applicable.
    async fn get_artists<
        'country_code,
        'include,
        'filter_left_square_bracket_handle_right_square_bracket,
        'filter_left_square_bracket_id_right_square_bracket,
    >(
        &self,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        filter_left_square_bracket_handle_right_square_bracket: Option<Vec<String>>,
        filter_left_square_bracket_id_right_square_bracket: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiResourceDataDocument, Error<GetArtistsError>>;

    /// PATCH /artists/{id}
    ///
    /// Updates existing artist.
    async fn patch_artist<'id, 'artist_update_body>(
        &self,
        id: &'id str,
        artist_update_body: Option<models::ArtistUpdateBody>,
    ) -> Result<(), Error<PatchArtistError>>;

    /// PATCH /artists/{id}/relationships/profileArt
    ///
    /// Updates profileArt relationship.
    async fn patch_artist_profile_art<
        'id,
        'artist_profile_art_relationship_update_operation_payload,
    >(
        &self,
        id: &'id str,
        artist_profile_art_relationship_update_operation_payload: Option<
            models::ArtistProfileArtRelationshipUpdateOperationPayload,
        >,
    ) -> Result<(), Error<PatchArtistProfileArtError>>;
}

#[derive(Clone)]
pub struct ArtistsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ArtistsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl ArtistsApi for ArtistsApiClient {
    /// Adds item(s) to following relationship.
    async fn add_artist_followers<
        'id,
        'country_code,
        'artist_following_relationship_add_operation_payload,
    >(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        artist_following_relationship_add_operation_payload: Option<
            models::ArtistFollowingRelationshipAddOperationPayload,
        >,
    ) -> Result<(), Error<AddArtistFollowersError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/following",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&artist_following_relationship_add_operation_payload);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AddArtistFollowersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Creates a new artist.
    async fn create_artist<'artist_create_operation_payload>(
        &self,
        artist_create_operation_payload: Option<models::ArtistCreateOperationPayload>,
    ) -> Result<models::ArtistsSingleResourceDataDocument, Error<CreateArtistError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/artists", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&artist_create_operation_payload);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsSingleResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsSingleResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<CreateArtistError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Deletes item(s) from following relationship.
    async fn delete_artist_followers<
        'id,
        'artist_following_relationship_remove_operation_payload,
    >(
        &self,
        id: &'id str,
        artist_following_relationship_remove_operation_payload: Option<
            models::ArtistFollowingRelationshipRemoveOperationPayload,
        >,
    ) -> Result<(), Error<DeleteArtistFollowersError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/following",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&artist_following_relationship_remove_operation_payload);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteArtistFollowersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves single artist by id.
    async fn get_artist<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsSingleResourceDataDocument, Error<GetArtistError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsSingleResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsSingleResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves albums relationship.
    async fn get_artist_albums<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistAlbumsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/albums",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistAlbumsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves biography relationship.
    async fn get_artist_artist_biography<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsSingleRelationshipDataDocument, Error<GetArtistArtistBiographyError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/biography",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsSingleRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsSingleRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistArtistBiographyError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves roles relationship.
    async fn get_artist_artist_roles<'id, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistArtistRolesError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/roles",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistArtistRolesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves following relationship.
    async fn get_artist_follower<'id, 'viewer_context, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        viewer_context: Option<&'viewer_context str>,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsFollowingMultiRelationshipDataDocument, Error<GetArtistFollowerError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/following",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = viewer_context {
            local_var_req_builder =
                local_var_req_builder.query(&[("viewerContext", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsFollowingMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsFollowingMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistFollowerError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves followers relationship.
    async fn get_artist_followers<'id, 'viewer_context, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        viewer_context: Option<&'viewer_context str>,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsFollowersMultiRelationshipDataDocument, Error<GetArtistFollowersError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/followers",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = viewer_context {
            local_var_req_builder =
                local_var_req_builder.query(&[("viewerContext", &param_value.to_string())]);
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsFollowersMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsFollowersMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistFollowersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves owners relationship.
    async fn get_artist_owners<'id, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistOwnersError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/owners",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistOwnersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves profileArt relationship.
    async fn get_artist_profile_art<'id, 'country_code, 'include, 'page_cursor>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        page_cursor: Option<&'page_cursor str>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistProfileArtError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/profileArt",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistProfileArtError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves radio relationship.
    async fn get_artist_radio<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistRadioError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/radio",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistRadioError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves similarArtists relationship.
    async fn get_artist_similar_artists<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistSimilarArtistsError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/similarArtists",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistSimilarArtistsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves trackProviders relationship.
    async fn get_artist_track_providers<'id, 'page_cursor, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        include: Option<Vec<String>>,
    ) -> Result<
        models::ArtistsTrackProvidersMultiRelationshipDataDocument,
        Error<GetArtistTrackProvidersError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/trackProviders",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsTrackProvidersMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsTrackProvidersMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistTrackProvidersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves tracks relationship.
    async fn get_artist_tracks<'id, 'collapse_by, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        collapse_by: &'collapse_by str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistTracksError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/tracks",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("collapseBy", &collapse_by.to_string())]);
        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistTracksError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves videos relationship.
    async fn get_artist_videos<'id, 'page_cursor, 'country_code, 'include>(
        &self,
        id: &'id str,
        page_cursor: Option<&'page_cursor str>,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiRelationshipDataDocument, Error<GetArtistVideosError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/videos",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_cursor {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistVideosError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves multiple artists by available filters, or without if applicable.
    async fn get_artists<
        'country_code,
        'include,
        'filter_left_square_bracket_handle_right_square_bracket,
        'filter_left_square_bracket_id_right_square_bracket,
    >(
        &self,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        filter_left_square_bracket_handle_right_square_bracket: Option<Vec<String>>,
        filter_left_square_bracket_id_right_square_bracket: Option<Vec<String>>,
    ) -> Result<models::ArtistsMultiResourceDataDocument, Error<GetArtistsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/artists", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = filter_left_square_bracket_handle_right_square_bracket {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("filter[handle]".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "filter[handle]",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = filter_left_square_bracket_id_right_square_bracket {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("filter[id]".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "filter[id]",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ArtistsMultiResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ArtistsMultiResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetArtistsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Updates existing artist.
    async fn patch_artist<'id, 'artist_update_body>(
        &self,
        id: &'id str,
        artist_update_body: Option<models::ArtistUpdateBody>,
    ) -> Result<(), Error<PatchArtistError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&artist_update_body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PatchArtistError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Updates profileArt relationship.
    async fn patch_artist_profile_art<
        'id,
        'artist_profile_art_relationship_update_operation_payload,
    >(
        &self,
        id: &'id str,
        artist_profile_art_relationship_update_operation_payload: Option<
            models::ArtistProfileArtRelationshipUpdateOperationPayload,
        >,
    ) -> Result<(), Error<PatchArtistProfileArtError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/artists/{id}/relationships/profileArt",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&artist_profile_art_relationship_update_operation_payload);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PatchArtistProfileArtError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`ArtistsApi::add_artist_followers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddArtistFollowersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::create_artist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateArtistError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::delete_artist_followers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteArtistFollowersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_albums`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistAlbumsError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_artist_biography`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistArtistBiographyError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_artist_roles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistArtistRolesError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_follower`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistFollowerError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_followers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistFollowersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_owners`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistOwnersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_profile_art`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistProfileArtError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_radio`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistRadioError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_similar_artists`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistSimilarArtistsError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_track_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistTrackProvidersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_tracks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistTracksError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artist_videos`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistVideosError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::get_artists`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetArtistsError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::patch_artist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchArtistError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`ArtistsApi::patch_artist_profile_art`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchArtistProfileArtError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}
