/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait UserRecommendationsApi: Send + Sync {

    /// GET /userRecommendations/{id}
    ///
    /// Retrieves single userRecommendation by id.
    async fn get_user_recommendation<'id, 'country_code, 'locale, 'include>(&self, id: &'id str, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsSingleResourceDataDocument, Error<GetUserRecommendationError>>;

    /// GET /userRecommendations/{id}/relationships/discoveryMixes
    ///
    /// Retrieves discoveryMixes relationship.
    async fn get_user_recommendation_discovery_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationDiscoveryMixesError>>;

    /// GET /userRecommendations/{id}/relationships/myMixes
    ///
    /// Retrieves myMixes relationship.
    async fn get_user_recommendation_my_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationMyMixesError>>;

    /// GET /userRecommendations/{id}/relationships/newArrivalMixes
    ///
    /// Retrieves newArrivalMixes relationship.
    async fn get_user_recommendation_new_arrival_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationNewArrivalMixesError>>;
}

pub struct UserRecommendationsApiClient {
    configuration: Arc<configuration::Configuration>
}

impl UserRecommendationsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl UserRecommendationsApi for UserRecommendationsApiClient {
    /// Retrieves single userRecommendation by id.
    async fn get_user_recommendation<'id, 'country_code, 'locale, 'include>(&self, id: &'id str, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsSingleResourceDataDocument, Error<GetUserRecommendationError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/userRecommendations/{id}", local_var_configuration.base_path, id=crate::apis::urlencode(id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder = local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = locale {
            local_var_req_builder = local_var_req_builder.query(&[("locale", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserRecommendationsSingleResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UserRecommendationsSingleResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetUserRecommendationError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves discoveryMixes relationship.
    async fn get_user_recommendation_discovery_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationDiscoveryMixesError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/userRecommendations/{id}/relationships/discoveryMixes", local_var_configuration.base_path, id=crate::apis::urlencode(id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder = local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder = local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = locale {
            local_var_req_builder = local_var_req_builder.query(&[("locale", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetUserRecommendationDiscoveryMixesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves myMixes relationship.
    async fn get_user_recommendation_my_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationMyMixesError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/userRecommendations/{id}/relationships/myMixes", local_var_configuration.base_path, id=crate::apis::urlencode(id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder = local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder = local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = locale {
            local_var_req_builder = local_var_req_builder.query(&[("locale", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetUserRecommendationMyMixesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves newArrivalMixes relationship.
    async fn get_user_recommendation_new_arrival_mixes<'id, 'page_left_square_bracket_cursor_right_square_bracket, 'country_code, 'locale, 'include>(&self, id: &'id str, page_left_square_bracket_cursor_right_square_bracket: Option<&'page_left_square_bracket_cursor_right_square_bracket str>, country_code: Option<&'country_code str>, locale: Option<&'locale str>, include: Option<Vec<String>>) -> Result<models::UserRecommendationsMultiRelationshipDataDocument, Error<GetUserRecommendationNewArrivalMixesError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/userRecommendations/{id}/relationships/newArrivalMixes", local_var_configuration.base_path, id=crate::apis::urlencode(id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder = local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder = local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = locale {
            local_var_req_builder = local_var_req_builder.query(&[("locale", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UserRecommendationsMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetUserRecommendationNewArrivalMixesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`UserRecommendationsApi::get_user_recommendation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserRecommendationError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`UserRecommendationsApi::get_user_recommendation_discovery_mixes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserRecommendationDiscoveryMixesError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`UserRecommendationsApi::get_user_recommendation_my_mixes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserRecommendationMyMixesError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`UserRecommendationsApi::get_user_recommendation_new_arrival_mixes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserRecommendationNewArrivalMixesError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

