/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait UserReportsApi: Send + Sync {

    /// POST /userReports
    ///
    /// Creates a new userReport.
    async fn create_user_report<'user_report_create_operation_payload>(&self, user_report_create_operation_payload: Option<models::UserReportCreateOperationPayload>) -> Result<models::UserReportsSingleResourceDataDocument, Error<CreateUserReportError>>;
}

pub struct UserReportsApiClient {
    configuration: Arc<configuration::Configuration>
}

impl UserReportsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl UserReportsApi for UserReportsApiClient {
    /// Creates a new userReport.
    async fn create_user_report<'user_report_create_operation_payload>(&self, user_report_create_operation_payload: Option<models::UserReportCreateOperationPayload>) -> Result<models::UserReportsSingleResourceDataDocument, Error<CreateUserReportError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/userReports", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&user_report_create_operation_payload);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserReportsSingleResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UserReportsSingleResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<CreateUserReportError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`UserReportsApi::create_user_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateUserReportError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

