/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait VideosApi: Send + Sync {
    /// GET /videos/{id}
    ///
    /// Retrieves single video by id.
    async fn get_video<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosSingleResourceDataDocument, Error<GetVideoError>>;

    /// GET /videos/{id}/relationships/albums
    ///
    /// Retrieves albums relationship.
    async fn get_video_albums<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoAlbumsError>>;

    /// GET /videos/{id}/relationships/artists
    ///
    /// Retrieves artists relationship.
    async fn get_video_artists<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoArtistsError>>;

    /// GET /videos/{id}/relationships/providers
    ///
    /// Retrieves providers relationship.
    async fn get_video_providers<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoProvidersError>>;

    /// GET /videos/{id}/relationships/replacement
    ///
    /// Retrieves replacement relationship.
    async fn get_video_replacement_relationship<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<
        models::VideosSingleRelationshipDataDocument,
        Error<GetVideoReplacementRelationshipError>,
    >;

    /// GET /videos/{id}/relationships/thumbnailArt
    ///
    /// Retrieves thumbnailArt relationship.
    async fn get_video_thumbnail_art<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoThumbnailArtError>>;

    /// GET /videos
    ///
    /// Retrieves multiple videos by available filters, or without if applicable.
    async fn get_videos<
        'country_code,
        'include,
        'filter_left_square_bracket_id_right_square_bracket,
        'filter_left_square_bracket_isrc_right_square_bracket,
    >(
        &self,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        filter_left_square_bracket_id_right_square_bracket: Option<Vec<String>>,
        filter_left_square_bracket_isrc_right_square_bracket: Option<Vec<String>>,
    ) -> Result<models::VideosMultiResourceDataDocument, Error<GetVideosError>>;
}

#[derive(Clone)]
pub struct VideosApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl VideosApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl VideosApi for VideosApiClient {
    /// Retrieves single video by id.
    async fn get_video<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosSingleResourceDataDocument, Error<GetVideoError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosSingleResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosSingleResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves albums relationship.
    async fn get_video_albums<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoAlbumsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}/relationships/albums",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoAlbumsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves artists relationship.
    async fn get_video_artists<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoArtistsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}/relationships/artists",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoArtistsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves providers relationship.
    async fn get_video_providers<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoProvidersError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}/relationships/providers",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoProvidersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves replacement relationship.
    async fn get_video_replacement_relationship<'id, 'country_code, 'include>(
        &self,
        id: &'id str,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<
        models::VideosSingleRelationshipDataDocument,
        Error<GetVideoReplacementRelationshipError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}/relationships/replacement",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosSingleRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosSingleRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoReplacementRelationshipError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves thumbnailArt relationship.
    async fn get_video_thumbnail_art<
        'id,
        'page_left_square_bracket_cursor_right_square_bracket,
        'country_code,
        'include,
    >(
        &self,
        id: &'id str,
        page_left_square_bracket_cursor_right_square_bracket: Option<
            &'page_left_square_bracket_cursor_right_square_bracket str,
        >,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
    ) -> Result<models::VideosMultiRelationshipDataDocument, Error<GetVideoThumbnailArtError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/videos/{id}/relationships/thumbnailArt",
            local_var_configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = page_left_square_bracket_cursor_right_square_bracket {
            local_var_req_builder =
                local_var_req_builder.query(&[("page[cursor]", &param_value.to_string())]);
        }
        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosMultiRelationshipDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideoThumbnailArtError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves multiple videos by available filters, or without if applicable.
    async fn get_videos<
        'country_code,
        'include,
        'filter_left_square_bracket_id_right_square_bracket,
        'filter_left_square_bracket_isrc_right_square_bracket,
    >(
        &self,
        country_code: Option<&'country_code str>,
        include: Option<Vec<String>>,
        filter_left_square_bracket_id_right_square_bracket: Option<Vec<String>>,
        filter_left_square_bracket_isrc_right_square_bracket: Option<Vec<String>>,
    ) -> Result<models::VideosMultiResourceDataDocument, Error<GetVideosError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = country_code {
            local_var_req_builder =
                local_var_req_builder.query(&[("countryCode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = include {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("include".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "include",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = filter_left_square_bracket_id_right_square_bracket {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("filter[id]".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "filter[id]",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = filter_left_square_bracket_isrc_right_square_bracket {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("filter[isrc]".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "filter[isrc]",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&local_var_content)).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideosMultiResourceDataDocument`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideosMultiResourceDataDocument`")))),
            }
        } else {
            let local_var_entity: Option<GetVideosError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`VideosApi::get_video`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_video_albums`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoAlbumsError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_video_artists`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoArtistsError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_video_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoProvidersError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_video_replacement_relationship`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoReplacementRelationshipError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_video_thumbnail_art`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideoThumbnailArtError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get_videos`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVideosError {
    Status400(models::Default400ResponseBody),
    Status404(models::Default404ResponseBody),
    Status405(models::Default405ResponseBody),
    Status406(models::Default406ResponseBody),
    Status415(models::Default415ResponseBody),
    Status429(models::Default429ResponseBody),
    Status500(models::Default500ResponseBody),
    Status503(models::Default503ResponseBody),
    UnknownValue(serde_json::Value),
}
