/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AlbumCoverArtRelationshipUpdateOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AlbumCoverArtRelationshipUpdateOperationPayloadData {
    pub fn new(id: String, r#type: Type) -> AlbumCoverArtRelationshipUpdateOperationPayloadData {
        AlbumCoverArtRelationshipUpdateOperationPayloadData { id, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "artworks")]
    Artworks,
}

impl Default for Type {
    fn default() -> Type {
        Self::Artworks
    }
}
