/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AlbumUpdateOperationPayloadData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::AlbumUpdateOperationPayloadDataAttributes>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<models::AlbumUpdateOperationPayloadDataRelationships>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AlbumUpdateOperationPayloadData {
    pub fn new(id: String, r#type: Type) -> AlbumUpdateOperationPayloadData {
        AlbumUpdateOperationPayloadData {
            attributes: None,
            id,
            relationships: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "albums")]
    Albums,
}

impl Default for Type {
    fn default() -> Type {
        Self::Albums
    }
}

