/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistBiographyUpdateBodyData {
    #[serde(rename = "attributes")]
    pub attributes: Box<models::ArtistBiographyUpdateBodyDataAttributes>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ArtistBiographyUpdateBodyData {
    pub fn new(attributes: models::ArtistBiographyUpdateBodyDataAttributes, id: String, r#type: Type) -> ArtistBiographyUpdateBodyData {
        ArtistBiographyUpdateBodyData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "artistBiographies")]
    ArtistBiographies,
}

impl Default for Type {
    fn default() -> Type {
        Self::ArtistBiographies
    }
}

