/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistClaimsUpdateOperationPayload {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::ArtistClaimsUpdateOperationPayloadData>>,
    #[serde(rename = "meta")]
    pub meta: Box<models::ArtistClaimsUpdateOperationPayloadMeta>,
}

impl ArtistClaimsUpdateOperationPayload {
    pub fn new(meta: models::ArtistClaimsUpdateOperationPayloadMeta) -> ArtistClaimsUpdateOperationPayload {
        ArtistClaimsUpdateOperationPayload {
            data: None,
            meta: Box::new(meta),
        }
    }
}

