/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Attributes {
    #[serde(rename = "collectionType")]
    pub collection_type: CollectionType,
    #[serde(rename = "name")]
    pub name: String,
}

impl Attributes {
    pub fn new(collection_type: CollectionType, name: String) -> Attributes {
        Attributes {
            collection_type,
            name,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CollectionType {
    #[serde(rename = "PLAYLISTS")]
    Playlists,
}

impl Default for CollectionType {
    fn default() -> CollectionType {
        Self::Playlists
    }
}

