/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioNormalizationData : Track normalization data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AudioNormalizationData {
    #[serde(rename = "peakAmplitude", skip_serializing_if = "Option::is_none")]
    pub peak_amplitude: Option<f32>,
    #[serde(rename = "replayGain", skip_serializing_if = "Option::is_none")]
    pub replay_gain: Option<f32>,
}

impl AudioNormalizationData {
    /// Track normalization data
    pub fn new() -> AudioNormalizationData {
        AudioNormalizationData {
            peak_amplitude: None,
            replay_gain: None,
        }
    }
}

