/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BarcodeId : Barcode Id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct BarcodeId {
    #[serde(rename = "value")]
    pub value: String,
}

impl BarcodeId {
    /// Barcode Id
    pub fn new(value: String) -> BarcodeId {
        BarcodeId {
            value,
        }
    }
}

