/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct CreateReactionPayloadData {
    #[serde(rename = "attributes")]
    pub attributes: Box<models::CreateReactionPayloadDataAttributes>,
    #[serde(rename = "relationships")]
    pub relationships: Box<models::CreateReactionPayloadDataRelationships>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CreateReactionPayloadData {
    pub fn new(attributes: models::CreateReactionPayloadDataAttributes, relationships: models::CreateReactionPayloadDataRelationships, r#type: Type) -> CreateReactionPayloadData {
        CreateReactionPayloadData {
            attributes: Box::new(attributes),
            relationships: Box::new(relationships),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "reactions")]
    Reactions,
}

impl Default for Type {
    fn default() -> Type {
        Self::Reactions
    }
}

