/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum IncludedInner {
    #[serde(rename="albums")]
    Albums(Box<models::AlbumsResourceObject>),
    #[serde(rename="appreciations")]
    Appreciations(Box<models::AppreciationsResourceObject>),
    #[serde(rename="artistBiographies")]
    ArtistBiographies(Box<models::ArtistBiographiesResourceObject>),
    #[serde(rename="artistClaims")]
    ArtistClaims(Box<models::ArtistClaimsResourceObject>),
    #[serde(rename="artistRoles")]
    ArtistRoles(Box<models::ArtistRolesResourceObject>),
    #[serde(rename="artists")]
    Artists(Box<models::ArtistsResourceObject>),
    #[serde(rename="artworks")]
    Artworks(Box<models::ArtworksResourceObject>),
    #[serde(rename="dynamicPages")]
    DynamicPages(Box<models::DynamicPagesResourceObject>),
    #[serde(rename="genres")]
    Genres(Box<models::GenresResourceObject>),
    #[serde(rename="lyrics")]
    Lyrics(Box<models::LyricsResourceObject>),
    #[serde(rename="manualArtistClaims")]
    ManualArtistClaims(Box<models::ManualArtistClaimsResourceObject>),
    #[serde(rename="playQueues")]
    PlayQueues(Box<models::PlayQueuesResourceObject>),
    #[serde(rename="playlists")]
    Playlists(Box<models::PlaylistsResourceObject>),
    #[serde(rename="providers")]
    Providers(Box<models::ProvidersResourceObject>),
    #[serde(rename="reactions")]
    Reactions(Box<models::ReactionsResourceObject>),
    #[serde(rename="savedShares")]
    SavedShares(Box<models::SavedSharesResourceObject>),
    #[serde(rename="searchResults")]
    SearchResults(Box<models::SearchResultsResourceObject>),
    #[serde(rename="searchSuggestions")]
    SearchSuggestions(Box<models::SearchSuggestionsResourceObject>),
    #[serde(rename="shares")]
    Shares(Box<models::SharesResourceObject>),
    #[serde(rename="stripeConnections")]
    StripeConnections(Box<models::StripeConnectionsResourceObject>),
    #[serde(rename="trackFiles")]
    TrackFiles(Box<models::TrackFilesResourceObject>),
    #[serde(rename="trackManifests")]
    TrackManifests(Box<models::TrackManifestsResourceObject>),
    #[serde(rename="trackSourceFiles")]
    TrackSourceFiles(Box<models::TrackSourceFilesResourceObject>),
    #[serde(rename="trackStatistics")]
    TrackStatistics(Box<models::TrackStatisticsResourceObject>),
    #[serde(rename="tracks")]
    Tracks(Box<models::TracksResourceObject>),
    #[serde(rename="userCollectionFolders")]
    UserCollectionFolders(Box<models::UserCollectionFoldersResourceObject>),
    #[serde(rename="userCollections")]
    UserCollections(Box<models::UserCollectionsResourceObject>),
    #[serde(rename="userEntitlements")]
    UserEntitlements(Box<models::UserEntitlementsResourceObject>),
    #[serde(rename="userRecommendations")]
    UserRecommendations(Box<models::UserRecommendationsResourceObject>),
    #[serde(rename="userReports")]
    UserReports(Box<models::UserReportsResourceObject>),
    #[serde(rename="users")]
    Users(Box<models::UsersResourceObject>),
    #[serde(rename="videos")]
    Videos(Box<models::VideosResourceObject>),
}

impl Default for IncludedInner {
    fn default() -> Self {
        Self::Albums(Default::default())
    }
}


