/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LyricsCreateOperationPayloadData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::LyricsCreateOperationPayloadDataAttributes>>,
    #[serde(rename = "relationships")]
    pub relationships: Box<models::LyricsCreateOperationPayloadDataRelationships>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl LyricsCreateOperationPayloadData {
    pub fn new(relationships: models::LyricsCreateOperationPayloadDataRelationships, r#type: Type) -> LyricsCreateOperationPayloadData {
        LyricsCreateOperationPayloadData {
            attributes: None,
            relationships: Box::new(relationships),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lyrics")]
    Lyrics,
}

impl Default for Type {
    fn default() -> Type {
        Self::Lyrics
    }
}

