/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LyricsAttributesProvider {
    ThirdPartyLyricsProvider(Box<models::ThirdPartyLyricsProvider>),
    TidalLyricsProvider(Box<models::TidalLyricsProvider>),
}

impl Default for LyricsAttributesProvider {
    fn default() -> Self {
        Self::ThirdPartyLyricsProvider(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "TIDAL")]
    Tidal,
    #[serde(rename = "THIRD_PARTY")]
    ThirdParty,
}

impl Default for Source {
    fn default() -> Source {
        Self::Tidal
    }
}

