/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualArtistClaimsCreateOperationPayloadDataAttributes {
    #[serde(rename = "acceptedTerms", skip_serializing_if = "Option::is_none")]
    pub accepted_terms: Option<bool>,
    #[serde(rename = "artistId")]
    pub artist_id: String,
    #[serde(rename = "distributorName", skip_serializing_if = "Option::is_none")]
    pub distributor_name: Option<String>,
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    #[serde(rename = "labelContactEmail", skip_serializing_if = "Option::is_none")]
    pub label_contact_email: Option<String>,
    #[serde(rename = "labelContactName", skip_serializing_if = "Option::is_none")]
    pub label_contact_name: Option<String>,
    #[serde(rename = "labelName", skip_serializing_if = "Option::is_none")]
    pub label_name: Option<String>,
    #[serde(rename = "legalFirstName")]
    pub legal_first_name: String,
    #[serde(rename = "legalLastName")]
    pub legal_last_name: String,
    #[serde(rename = "managerEmail", skip_serializing_if = "Option::is_none")]
    pub manager_email: Option<String>,
    #[serde(rename = "managerName", skip_serializing_if = "Option::is_none")]
    pub manager_name: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "selectedAlbums", skip_serializing_if = "Option::is_none")]
    pub selected_albums: Option<Vec<String>>,
    #[serde(rename = "selectedSingles", skip_serializing_if = "Option::is_none")]
    pub selected_singles: Option<Vec<String>>,
    #[serde(rename = "websiteOrSocialLink")]
    pub website_or_social_link: String,
}

impl ManualArtistClaimsCreateOperationPayloadDataAttributes {
    pub fn new(artist_id: String, legal_first_name: String, legal_last_name: String, website_or_social_link: String) -> ManualArtistClaimsCreateOperationPayloadDataAttributes {
        ManualArtistClaimsCreateOperationPayloadDataAttributes {
            accepted_terms: None,
            artist_id,
            distributor_name: None,
            error_reason: None,
            label_contact_email: None,
            label_contact_name: None,
            label_name: None,
            legal_first_name,
            legal_last_name,
            manager_email: None,
            manager_name: None,
            role: None,
            selected_albums: None,
            selected_singles: None,
            website_or_social_link,
        }
    }
}

