/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ManualArtistClaimsAttributes {
    /// Accepted terms and conditions
    #[serde(rename = "acceptedTerms", skip_serializing_if = "Option::is_none")]
    pub accepted_terms: Option<bool>,
    /// Artist ID being claimed
    #[serde(rename = "artistId")]
    pub artist_id: String,
    /// Timestamp when the claim was created
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Distributor name
    #[serde(rename = "distributorName", skip_serializing_if = "Option::is_none")]
    pub distributor_name: Option<String>,
    /// Enrollment type
    #[serde(rename = "enrollmentType", skip_serializing_if = "Option::is_none")]
    pub enrollment_type: Option<String>,
    /// Error reason if claim failed
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    /// Label contact email
    #[serde(rename = "labelContactEmail", skip_serializing_if = "Option::is_none")]
    pub label_contact_email: Option<String>,
    /// Label contact name
    #[serde(rename = "labelContactName", skip_serializing_if = "Option::is_none")]
    pub label_contact_name: Option<String>,
    /// Label name
    #[serde(rename = "labelName", skip_serializing_if = "Option::is_none")]
    pub label_name: Option<String>,
    /// Timestamp when the claim was last modified
    #[serde(rename = "lastModifiedAt", skip_serializing_if = "Option::is_none")]
    pub last_modified_at: Option<String>,
    /// Legal first name
    #[serde(rename = "legalFirstName")]
    pub legal_first_name: String,
    /// Legal last name
    #[serde(rename = "legalLastName")]
    pub legal_last_name: String,
    /// Manager email
    #[serde(rename = "managerEmail", skip_serializing_if = "Option::is_none")]
    pub manager_email: Option<String>,
    /// Manager name
    #[serde(rename = "managerName", skip_serializing_if = "Option::is_none")]
    pub manager_name: Option<String>,
    /// Role
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Album IDs selected by user
    #[serde(rename = "selectedAlbums", skip_serializing_if = "Option::is_none")]
    pub selected_albums: Option<Vec<String>>,
    /// Single IDs selected by user
    #[serde(rename = "selectedSingles", skip_serializing_if = "Option::is_none")]
    pub selected_singles: Option<Vec<String>>,
    /// Claim status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Website or social link
    #[serde(rename = "websiteOrSocialLink")]
    pub website_or_social_link: String,
}

impl ManualArtistClaimsAttributes {
    pub fn new(artist_id: String, legal_first_name: String, legal_last_name: String, website_or_social_link: String) -> ManualArtistClaimsAttributes {
        ManualArtistClaimsAttributes {
            accepted_terms: None,
            artist_id,
            created_at: None,
            distributor_name: None,
            enrollment_type: None,
            error_reason: None,
            label_contact_email: None,
            label_contact_name: None,
            label_name: None,
            last_modified_at: None,
            legal_first_name,
            legal_last_name,
            manager_email: None,
            manager_name: None,
            role: None,
            selected_albums: None,
            selected_singles: None,
            status: None,
            website_or_social_link,
        }
    }
}
/// Claim status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

