/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct PlayQueuesRelationships {
    #[serde(rename = "current")]
    pub current: Box<models::PlayQueuesCurrentSingleRelationshipDataDocument>,
    #[serde(rename = "future")]
    pub future: Box<models::PlayQueuesFutureMultiRelationshipDataDocument>,
    #[serde(rename = "owners")]
    pub owners: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "past")]
    pub past: Box<models::PlayQueuesPastMultiRelationshipDataDocument>,
}

impl PlayQueuesRelationships {
    pub fn new(current: models::PlayQueuesCurrentSingleRelationshipDataDocument, future: models::PlayQueuesFutureMultiRelationshipDataDocument, owners: models::MultiRelationshipDataDocument, past: models::PlayQueuesPastMultiRelationshipDataDocument) -> PlayQueuesRelationships {
        PlayQueuesRelationships {
            current: Box::new(current),
            future: Box::new(future),
            owners: Box::new(owners),
            past: Box::new(past),
        }
    }
}

