/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayQueueUpdateFutureOperationPayloadMeta {
    #[serde(rename = "positionBefore")]
    pub position_before: String,
}

impl PlayQueueUpdateFutureOperationPayloadMeta {
    pub fn new(position_before: String) -> PlayQueueUpdateFutureOperationPayloadMeta {
        PlayQueueUpdateFutureOperationPayloadMeta {
            position_before,
        }
    }
}

