/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistUpdateOperationPayloadData {
    #[serde(rename = "attributes")]
    pub attributes: Box<models::PlaylistUpdateOperationPayloadDataAttributes>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PlaylistUpdateOperationPayloadData {
    pub fn new(attributes: models::PlaylistUpdateOperationPayloadDataAttributes, id: String, r#type: Type) -> PlaylistUpdateOperationPayloadData {
        PlaylistUpdateOperationPayloadData {
            attributes: Box::new(attributes),
            id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "playlists")]
    Playlists,
}

impl Default for Type {
    fn default() -> Type {
        Self::Playlists
    }
}

