/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReactionsRelationships {
    #[serde(rename = "ownerProfiles")]
    pub owner_profiles: Box<models::MultiRelationshipDataDocument>,
}

impl ReactionsRelationships {
    pub fn new(owner_profiles: models::MultiRelationshipDataDocument) -> ReactionsRelationships {
        ReactionsRelationships {
            owner_profiles: Box::new(owner_profiles),
        }
    }
}

