/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SavedSharesAttributes {
    /// Datetime of saved share creation (ISO 8601)
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl SavedSharesAttributes {
    pub fn new(created_at: String) -> SavedSharesAttributes {
        SavedSharesAttributes {
            created_at,
        }
    }
}

