/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SearchSuggestionsRelationships {
    #[serde(rename = "directHits")]
    pub direct_hits: Box<models::MultiRelationshipDataDocument>,
}

impl SearchSuggestionsRelationships {
    pub fn new(direct_hits: models::MultiRelationshipDataDocument) -> SearchSuggestionsRelationships {
        SearchSuggestionsRelationships {
            direct_hits: Box::new(direct_hits),
        }
    }
}

