/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSuggestionsResourceObject {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::SearchSuggestionsAttributes>>,
    /// Resource id
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<models::SearchSuggestionsRelationships>>,
    /// Resource type
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SearchSuggestionsResourceObject {
    pub fn new(id: String, r#type: String) -> SearchSuggestionsResourceObject {
        SearchSuggestionsResourceObject {
            attributes: None,
            id,
            relationships: None,
            r#type,
        }
    }
}

