/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchSuggestionsHistory : Suggestions from search history
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSuggestionsHistory {
    #[serde(rename = "highlights", skip_serializing_if = "Option::is_none")]
    pub highlights: Option<Vec<models::SearchSuggestionsHighlights>>,
    #[serde(rename = "query")]
    pub query: String,
}

impl SearchSuggestionsHistory {
    /// Suggestions from search history
    pub fn new(query: String) -> SearchSuggestionsHistory {
        SearchSuggestionsHistory {
            highlights: None,
            query,
        }
    }
}

