/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StripeConnectionsAttributes {
    /// Timestamp when the connection was created
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// External links for Stripe connection
    #[serde(rename = "externalLinks", skip_serializing_if = "Option::is_none")]
    pub external_links: Option<Vec<models::ExternalLink>>,
    /// Timestamp when the connection was last modified
    #[serde(rename = "lastModifiedAt", skip_serializing_if = "Option::is_none")]
    pub last_modified_at: Option<String>,
    /// Current status of this Stripe connection
    #[serde(rename = "status")]
    pub status: Status,
}

impl StripeConnectionsAttributes {
    pub fn new(status: Status) -> StripeConnectionsAttributes {
        StripeConnectionsAttributes {
            created_at: None,
            external_links: None,
            last_modified_at: None,
            status,
        }
    }
}
/// Current status of this Stripe connection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING_REQUIREMENTS")]
    PendingRequirements,
    #[serde(rename = "UNDER_REVIEW")]
    UnderReview,
    #[serde(rename = "ACCEPTED")]
    Accepted,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for Status {
    fn default() -> Status {
        Self::PendingRequirements
    }
}

