/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThirdPartyLyricsProvider {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
    #[serde(rename = "commonTrackId")]
    pub common_track_id: String,
    #[serde(rename = "lyricsId")]
    pub lyrics_id: String,
}

impl ThirdPartyLyricsProvider {
    pub fn new(name: String, common_track_id: String, lyrics_id: String) -> ThirdPartyLyricsProvider {
        ThirdPartyLyricsProvider {
            name,
            source: None,
            common_track_id,
            lyrics_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "TIDAL")]
    Tidal,
    #[serde(rename = "THIRD_PARTY")]
    ThirdParty,
}

impl Default for Source {
    fn default() -> Source {
        Self::Tidal
    }
}

