/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackStatisticsAttributes {
    /// Total playbacks
    #[serde(rename = "totalPlaybacks")]
    pub total_playbacks: i32,
    /// Unique listeners
    #[serde(rename = "uniqueListeners")]
    pub unique_listeners: i32,
}

impl TrackStatisticsAttributes {
    pub fn new(total_playbacks: i32, unique_listeners: i32) -> TrackStatisticsAttributes {
        TrackStatisticsAttributes {
            total_playbacks,
            unique_listeners,
        }
    }
}

