/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TrackSourceFileCreateOperationPayloadData {
    #[serde(rename = "attributes")]
    pub attributes: Box<models::TrackSourceFileCreateOperationPayloadDataAttributes>,
    #[serde(rename = "relationships")]
    pub relationships: Box<models::TrackSourceFileCreateOperationPayloadDataRelationships>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TrackSourceFileCreateOperationPayloadData {
    pub fn new(attributes: models::TrackSourceFileCreateOperationPayloadDataAttributes, relationships: models::TrackSourceFileCreateOperationPayloadDataRelationships, r#type: Type) -> TrackSourceFileCreateOperationPayloadData {
        TrackSourceFileCreateOperationPayloadData {
            attributes: Box::new(attributes),
            relationships: Box::new(relationships),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "trackSourceFiles")]
    TrackSourceFiles,
}

impl Default for Type {
    fn default() -> Type {
        Self::TrackSourceFiles
    }
}

