/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackCreateOperationPayloadDataRelationships {
    #[serde(rename = "albums")]
    pub albums: Box<models::TrackCreateOperationPayloadDataRelationshipsAlbums>,
    #[serde(rename = "artists")]
    pub artists: Box<models::TrackCreateOperationPayloadDataRelationshipsArtists>,
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Box<models::TrackCreateOperationPayloadDataRelationshipsGenres>>,
}

impl TrackCreateOperationPayloadDataRelationships {
    pub fn new(albums: models::TrackCreateOperationPayloadDataRelationshipsAlbums, artists: models::TrackCreateOperationPayloadDataRelationshipsArtists) -> TrackCreateOperationPayloadDataRelationships {
        TrackCreateOperationPayloadDataRelationships {
            albums: Box::new(albums),
            artists: Box::new(artists),
            genres: None,
        }
    }
}

