/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TrackFilesReadById404ResponseBodyErrorsInner {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
}

impl TrackFilesReadById404ResponseBodyErrorsInner {
    pub fn new(code: Code, status: String) -> TrackFilesReadById404ResponseBodyErrorsInner {
        TrackFilesReadById404ResponseBodyErrorsInner {
            code,
            detail: None,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "CONTENT_NOT_FOUND")]
    ContentNotFound,
}

impl Default for Code {
    fn default() -> Code {
        Self::ContentNotFound
    }
}

