/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionFoldersAttributes {
    #[serde(rename = "collectionType")]
    pub collection_type: CollectionType,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "lastModifiedAt")]
    pub last_modified_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "numberOfItems", skip_serializing_if = "Option::is_none")]
    pub number_of_items: Option<i32>,
}

impl UserCollectionFoldersAttributes {
    pub fn new(collection_type: CollectionType, created_at: String, last_modified_at: String, name: String) -> UserCollectionFoldersAttributes {
        UserCollectionFoldersAttributes {
            collection_type,
            created_at,
            last_modified_at,
            name,
            number_of_items: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CollectionType {
    #[serde(rename = "PLAYLISTS")]
    Playlists,
}

impl Default for CollectionType {
    fn default() -> CollectionType {
        Self::Playlists
    }
}

