/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UserRecommendationsRelationships {
    #[serde(rename = "discoveryMixes")]
    pub discovery_mixes: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "myMixes")]
    pub my_mixes: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "newArrivalMixes")]
    pub new_arrival_mixes: Box<models::MultiRelationshipDataDocument>,
}

impl UserRecommendationsRelationships {
    pub fn new(discovery_mixes: models::MultiRelationshipDataDocument, my_mixes: models::MultiRelationshipDataDocument, new_arrival_mixes: models::MultiRelationshipDataDocument) -> UserRecommendationsRelationships {
        UserRecommendationsRelationships {
            discovery_mixes: Box::new(discovery_mixes),
            my_mixes: Box::new(my_mixes),
            new_arrival_mixes: Box::new(new_arrival_mixes),
        }
    }
}

