/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRecommendationsSingleResourceDataDocument {
    #[serde(rename = "data")]
    pub data: Box<models::UserRecommendationsResourceObject>,
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<models::IncludedInner>>,
    #[serde(rename = "links")]
    pub links: Box<models::Links>,
}

impl UserRecommendationsSingleResourceDataDocument {
    pub fn new(data: models::UserRecommendationsResourceObject, links: models::Links) -> UserRecommendationsSingleResourceDataDocument {
        UserRecommendationsSingleResourceDataDocument {
            data: Box::new(data),
            included: None,
            links: Box::new(links),
        }
    }
}

