/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionTracksRelationshipAddOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::UserCollectionTracksRelationshipAddOperationPayloadDataMeta>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl UserCollectionTracksRelationshipAddOperationPayloadData {
    pub fn new(id: String, r#type: Type) -> UserCollectionTracksRelationshipAddOperationPayloadData {
        UserCollectionTracksRelationshipAddOperationPayloadData {
            id,
            meta: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tracks")]
    Tracks,
}

impl Default for Type {
    fn default() -> Type {
        Self::Tracks
    }
}

