/*
 * TIDAL API
 *
 * The TIDAL API is a [JSON:API](https://jsonapi.org/)–compliant web API that exposes TIDAL’s music, metadata, and user-related functionality through a consistent, resource-oriented design. More information and API management are available at [developer.tidal.com](developer.tidal.com)
 *
 * The version of the OpenAPI document: 1.0.36
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct VideosRelationships {
    #[serde(rename = "albums")]
    pub albums: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "artists")]
    pub artists: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "providers")]
    pub providers: Box<models::MultiRelationshipDataDocument>,
    #[serde(rename = "replacement")]
    pub replacement: Box<models::SingleRelationshipDataDocument>,
    #[serde(rename = "thumbnailArt")]
    pub thumbnail_art: Box<models::MultiRelationshipDataDocument>,
}

impl VideosRelationships {
    pub fn new(albums: models::MultiRelationshipDataDocument, artists: models::MultiRelationshipDataDocument, providers: models::MultiRelationshipDataDocument, replacement: models::SingleRelationshipDataDocument, thumbnail_art: models::MultiRelationshipDataDocument) -> VideosRelationships {
        VideosRelationships {
            albums: Box::new(albums),
            artists: Box::new(artists),
            providers: Box::new(providers),
            replacement: Box::new(replacement),
            thumbnail_art: Box::new(thumbnail_art),
        }
    }
}

